// <auto-generated />
using System;
using FlightBookingService.User.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlightBookingService.Airline.Migrations
{
    [DbContext(typeof(AirlineServiceContext))]
    [Migration("20220418125402_AirlineFlightDetails")]
    partial class AirlineFlightDetails
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FlightBookingService.Airline.Models.AirlineFlightDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Airline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Flag")
                        .HasColumnType("int");

                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlightSeatRow")
                        .HasColumnType("int");

                    b.Property<DateTime>("FlightStartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FlightToDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromPlaceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Meal")
                        .HasColumnType("int");

                    b.Property<decimal>("TicketCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ToPlaceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalBusinessSeats")
                        .HasColumnType("int");

                    b.Property<int>("TotalNonBusinessSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AirlineFlightDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
