// <auto-generated />
using System;
using FlightBookingService.User.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlightBookingService.Airline.Migrations
{
    [DbContext(typeof(AirlineServiceContext))]
    [Migration("20220421100211_AirlineFirstMigration")]
    partial class AirlineFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FlightBookingService.Airline.Models.AirlineDetails", b =>
                {
                    b.Property<int>("AirlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AirlineNmae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsDelete")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("AirlineId");

                    b.ToTable("AirlineDetails");
                });

            modelBuilder.Entity("FlightBookingService.Airline.Models.AirlineFlightDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<decimal>("BusTicketCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlightSeatRow")
                        .HasColumnType("int");

                    b.Property<DateTime>("FlightStartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FlightToDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromPlaceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsDelete")
                        .HasColumnType("int");

                    b.Property<int>("Meal")
                        .HasColumnType("int");

                    b.Property<decimal>("NonBusTicketCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ToPlaceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalBusinessSeats")
                        .HasColumnType("int");

                    b.Property<int>("TotalNonBusinessSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.ToTable("AirlineFlightDetails");
                });

            modelBuilder.Entity("FlightBookingService.Airline.Models.FlightBookingDetails", b =>
                {
                    b.Property<int>("FlightBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("IsDelete")
                        .HasColumnType("int");

                    b.Property<int>("Journey")
                        .HasColumnType("int");

                    b.Property<double>("OneWayCost")
                        .HasColumnType("float");

                    b.Property<string>("PNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalBookSeats")
                        .HasColumnType("int");

                    b.Property<double>("TwoWayCost")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FlightBookingId");

                    b.ToTable("FlightBookingDetails");
                });

            modelBuilder.Entity("FlightBookingService.Airline.Models.UserBookingDetails", b =>
                {
                    b.Property<int>("UserBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Flag")
                        .HasColumnType("int");

                    b.Property<int>("FlightBookingId")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("Meal")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserBookingId");

                    b.ToTable("UserBookingDetails");
                });

            modelBuilder.Entity("FlightBookingService.Airline.Models.AirlineFlightDetails", b =>
                {
                    b.HasOne("FlightBookingService.Airline.Models.AirlineDetails", "Airlines")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airlines");
                });
#pragma warning restore 612, 618
        }
    }
}
